### ISSUE TITLE
How to set default Value to Calendar Picker

### ISSUE THREAD

**Issue by Rodolfo-XDR** [morrisjdev/ng-metro4#10]
I want to know how to set Default Value to Picker

When I set something the upcoming error appears 

**this.innerValue.format is not a function**

**Comment by morrisjdev** [comment]
If you want to set an initial value you can control it by using [(ngModel)]. The value has to be definied in the components code.

Or do you want to know how to control the value that is used when clicking the clear button?

**Comment by Rodolfo-XDR** [comment]
Yes, the initial value.

Right now I have it just like this: 
In my HTML:
`<m4-calendar-picker [(ngModel)]="form.date" name="date" [format]="format" [calendar-wide]="true" [dialog-mode]="true"></m4-calendar-picker>`

Now, in the component, using regular component of metro4, setting form.date as: '05/05/2020' sets the initial value. But on ng-metro4 I have it like: 
`public form = {
    ....
    date : '05/06/2020'
 }`

And pops out the error I wrote above, and doesn't set an initial value.

**Comment by morrisjdev** [comment]
Date has to be of type date or moment.Date

**Comment by Rodolfo-XDR** [comment]
¡Thank you!
