### ISSUE TITLE
Calendar Picker Clear

### ISSUE THREAD

**Issue by Rodolfo-XDR** [morrisjdev/ng-metro4#11]
- When Clearing a Calendar Picker and Submitting, returns the previous selected date.

- When clearing twice or more an error appears: 

> core.js:6210 ERROR TypeError: Cannot read property 'toLocaleDateString' of null
    at HTMLInputElement.calendarPicker.options.onChange (ng-metro4.js:3449)

**Comment by morrisjdev** [comment]
Thank you for reporting this. I'll investigate it.

**Comment by morrisjdev** [comment]
Thank you again for reporting this.
The problem is fixed in version 2.0.1
