### ISSUE TITLE
Error when building App

### ISSUE THREAD

**Issue by Rodolfo-XDR** [morrisjdev/ng-metro4#7]
ERROR in node_modules/ng-metro4/lib/base/let/let.directive.d.ts:5:9 - error TS1086: An accessor cannot be declared in an ambient context.

5     set m4Let(context: any);
          ~~~~~
node_modules/ng-metro4/lib/base/loading/loading-display.directive.d.ts:11:9 - error TS1086: An accessor cannot be declared in an ambient context.

11     set loading(val: any);
           ~~~~~~~
node_modules/ng-metro4/lib/base/loading/not-loading-display.directive.d.ts:11:9 - error TS1086: An accessor cannot be declared in an ambient context.

11     set notLoading(val: any);
           ~~~~~~~~~~
src/app/app.module.ts:6:30 - error TS2307: Cannot find module './app.component'.

6 import { AppComponent } from './app.component';

I'm using Angular CLI: 8.3.26 & Latest Node.JS

**Comment by morrisjdev** [comment]
Are you using version 2.0.0? Use 1.0.10. It is for Angular < version 9

**Comment by Rodolfo-XDR** [comment]
Yes, I was using 2.0.0, I already downgraded the version to 1.0.10 for Angular 8, thank you
