### ISSUE TITLE
Spinner min-value not workin when set min-value="0"

### ISSUE THREAD

**Issue by nsbrabelo** [morrisjdev/ng-metro4#8]
When i set min-value = 0 the spinner alow down to infinity and beyond.

this is my source:
<m4-spinner [disabled]="blockItem(product)" (change)="addItemToCart(product, index)" [(ngModel)]="product.quantity" [min-value]="0" [max-value]="cart.flavors"></m4-spinner>

i try set a variable min with value 0 in my TS file and set this variable in bind, but not working too.
when i set min-value 1 he work, but with 0 not.

**Comment by morrisjdev** [comment]
Thank you for reporting this. I'll take a look into it.

**Comment by morrisjdev** [comment]
Thank you again for reporting this.
The problem is fixed in version 2.0.1
